### ISSUE TITLE
Refine color fudge variables

### ISSUE THREAD

**Issue by BD103** [BotsBurgh/BOTSBURGH-FTC-2021-22#12]
Once we have a color sensor, the fudge variables will need to be re-adjusted for the new robot.

_Originally posted by @sambhavsaggi in https://github.com/BotsBurgh/BOTSBURGH-FTC-2021-22/pull/11#discussion_r779146988_

**Comment by 9p4** [comment]
Use the ColorSensorTelemetry opmode to determine optimal values.

**Comment by BD103** [comment]
Color sensors aren't being used in this year's robot, closing
