### ISSUE TITLE
Make package names uncapitalized

### ISSUE THREAD

**Issue by BD103** [BotsBurgh/BOTSBURGH-FTC-2021-22#5]
Java naming specs recommend all package names be uncapitalized.

_Please_

**Comment by 9p4** [comment]
Do you have a source for this?

**Comment by BD103** [comment]
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

**Comment by 9p4** [comment]
Can we trust that source?

> The information on this page is for Archive Purposes Only
> This page is not being actively maintained. Links within the documentation may not work and the information itself may no longer be valid. The last revision to this document was made on April 20, 1999

**Comment by BD103** [comment]
[Here](https://www.oreilly.com/library/view/java-8-pocket/9781491901083/ch01.html), [here](https://www.javatpoint.com/java-naming-conventions), [here](https://www.theserverside.com/feature/Java-naming-conventions-explained?amp=1), and [here](https://www.thoughtco.com/using-java-naming-conventions-2034199)

**Comment by 9p4** [comment]
Cool. Make a PR to fix it?
